### ISSUE TITLE
Crashes

### ISSUE THREAD

**Issue by IntoTheVoid-900** [iamrasel/lunar-launcher#1]
On swiping right, the app crashes and I am reprompted to chose my default launcher.

**Comment by iamrasel** [comment]
Can you please provide the **stacktrace** of that crash? Without figuring out the issue, I can't solve them. I haven't faced such problem yet, till now I personally tested this app in three different devices (Nokia, Samsung and Huawei).

**Comment by bloodyeyesblackblood** [comment]
It also crashes for me, when i swipe from left to right
here take my log
https://paste.evolution-x.org/2nGwdj

Also why buttons for letters? Would it possible to set a searchbar at the bottom in the near future?

**Comment by IntoTheVoid-900** [comment]
@iamrasel How do I get the stack trace? I am not a Dev, and have no idea what that is.

**Comment by iamrasel** [comment]
> It also crashes for me, when i swipe from left to right here take my log https://paste.evolution-x.org/2nGwdj

Thanks for the log. Go to the [Actions](https://github.com/iamrasel/lunar-launcher/actions) tab, download and install the latest build from there. Check and see if there's any crashing issue left. If it still crashes, please show me the log again.

> Also why buttons for letters? Would it possible to set a searchbar at the bottom in the near future?

Currently there's no plan like this. Because in my opinion, using those buttons are way more easier than tapping on a text field, keyboard popup and then typing. @bloodyeyesblackblood

**Comment by iamrasel** [comment]
> @iamrasel How do I get the stack trace? I am not a Dev, and have no idea what that is.

See [here](https://android-doc.github.io/tools/help/logcat.html). You'll need to use a pc to get crash logs via ADB. You can follow [this](https://www.xda-developers.com/install-adb-windows-macos-linux/) easy guide to install and use adb on your pc. @IntoTheVoid-900

**Comment by bloodyeyesblackblood** [comment]
@iamrasel for me the crash is fixed with update v15 👌

**Comment by IntoTheVoid-900** [comment]
The new update fixes it for me too, thanks.
