### ISSUE TITLE
unable to add app to quick start 

### ISSUE THREAD

**Issue by Sprintrio** [iamrasel/lunar-launcher#114]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

2.8.1.1

### Android version

android 11

### Steps to reproduce the bug

When I try to add a quick start app

### Expected behavior

To be able to add 6 apps to my quick start 

### Screenshots/Screen recordings

![Screenshot_20240125-183114](https://github.com/iamrasel/lunar-launcher/assets/117413658/c54e6e70-3c73-49c2-8ce9-71d5b5ba455b)
![Screenshot_20240125-183127](https://github.com/iamrasel/lunar-launcher/assets/117413658/c1c93fc5-d41c-4b5a-8749-f1e6251bf1c5)

**Comment by xusiai** [comment]
I am also unable to add applications to this menu. URLs and contacts work but no applications show up. Looking at the wiki it seems like you're supposed to be able to add applications to it? 

> Quick Access: Most of the launchers out there have a feature named Dock, which contains some of your favourite apps to launch easily. This screen has that thing, you can add upto six apps. And also three plus three favorite contacts and urls for easy access. Also you can control your device's brightness and audio volumes from here.

**Comment by JakobKohler** [comment]
I am also experiencing the same issue since the last update. It seems like all the functionality is still there with the only exception being the displaying of the apps. The apps I had in my quick launch still have their slot assigned but - like the others have said - do not show up when I open the "dock"

**Comment by fs-sifat** [comment]
The feature does indeed work.
You need to double tap on the home screen to get the list of favorite apps, instead of sliding up.

![Screenshot_20240226-213924-01.jpeg](https://github.com/iamrasel/lunar-launcher/assets/125657944/686accd7-cf19-4918-b8ec-4411054fc4c4)

![Screenshot_20240226-213933.png](https://github.com/iamrasel/lunar-launcher/assets/125657944/3102f84a-4178-4ace-adec-91de7312aa54)


But there's a dilemma: You can't use your double tap gesture to lock the device; You have to disable that feature to be able to open the dock(favorite apps shortcut).

You can enable/disable that feature from ..
Lunar Launcher Settings > Misc > Double Tap Action



The window that you opened(Quick Access) by sliding up on the home screen, holds contact shortcuts; Not the favorite apps.

Hope that helps.

**Comment by Sprintrio** [comment]
thanks!
