### ISSUE TITLE
Published on Play Store

### ISSUE THREAD

**Issue by vednig** [iamrasel/lunar-launcher#24]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have already checked the [WIKI](https://github.com/iamrasel/lunar-launcher/wiki) pages.
- [X] I have taken the time to fill in all the required details. I understand that the question will be dismissed otherwise.

### What is/are your question(s)?

Hi there, I am here to tell you that "the mysterious app on Play Store" has been published by me through my developer account on Play Store, when I couldn't find this app on Play Store.
I am working on it [here](https://github.com/vednig/lunar-launcher)
PS: BTW, I am still working on proving automatic rollouts to users through GitHub Actions on Play Store
Plus, all the money received via sales on Play Store could be added to help the project financially, if possible.

**Comment by iamrasel** [comment]
This app is **not meant to be sold**, this is why I published it on F-droid. There wouldn't be any problem from my side if you had served the app for **free** on Play Store, rather than selling it.

I am giving the users an option to support me, so that we both can be happy. But, if anyone buys/already bought it from Store, that person won't donate me anything for sure. So, I can't agree with you or support your initiative.

**Comment by iamrasel** [comment]
I really need support to get a new laptop for smooth developing, else maybe I wouldn't ask for any donations.

**Comment by vednig** [comment]
Yeah, you're right so I will be making the app **free on Play Store** plus there's still some work left on **automated publishing**. 
I have already made it free on Play Store, it is may take some time in showing.

**Comment by iamrasel** [comment]
> I have already made it free on Play Store

Even after one day, still showing as paid.

**Comment by vednig** [comment]
Finally, it's done!🎉
