### ISSUE TITLE
Animation Glitching

### ISSUE THREAD

**Issue by ThisIsBond** [iamrasel/lunar-launcher#32]
### Checklist

- [X] I made sure that there are **no existing issues** - [open](https://github.com/iamrasel/lunar-launcher/issues) or [closed](https://github.com/iamrasel/lunar-launcher/issues?q=is%3Aissue+is%3Aclosed) - which I could contribute my information to.
- [X] I have taken the time to fill in all the required details. I understand that the bug report will be dismissed otherwise.
- [X] This issue contains only one bug.

### App version

2.2

### Android version

Android 13

### Steps to reproduce the bug

The charging animation around the clock doesn't loop all round it. It breaks from the half way.Interestingly the animations works flawlessly while clock screen is not in focus.

### Screenshots/Screen recordings

https://user-images.githubusercontent.com/71921136/202678356-146f5134-5d75-493d-aba1-b75a69174d56.mp4

**Comment by iamrasel** [comment]
For me, the animation glitches after a certain time periodically. It happens because the percentage changes; so I think, there is no way to solve that glitch completely. I tried several tricks already and failed. Here, screen's focus shouldn't do any change.

So, can you reconfirm that the animation animates smoothly when that screen is not focused, but glitches continuously only if focused?

**Comment by ThisIsBond** [comment]
Yes, Animation animates smoothly when the main screen is not in focus. You can observe that in above submitted clip.

**Comment by iamrasel** [comment]
I assume #67 fixes this.
